version: '3'
services:
  api: # service名
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: api_database # database名
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: default
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  dbdata:
    driver: local
